### ISSUE TITLE
Simplify data summary

### ISSUE THREAD

**Issue by ybressler** [Broadway-Open-Data/MVP-FrontEnd#1]
Data summary is messy right now. let's simplify it.

**Comment by ybressler** [comment]
Finito. In review.

**Comment by ybressler** [comment]
Current (improved) data summary 
![Screen Shot 2020-08-02 at 9 56 46 AM](https://user-images.githubusercontent.com/40807730/89124638-863c9b80-d4a6-11ea-9abe-df915243793c.png)

**Comment by ybressler** [comment]
### Choose the one which is easiest to comprehend:

- [ ] `N No Intermissions`
![Screen Shot 2020-08-02 at 9 56 46 AM](https://user-images.githubusercontent.com/40807730/89124682-dc114380-d4a6-11ea-94a4-1bfa47998690.png)
- [ ] `N Intermissions == 0`
![Screen Shot 2020-08-02 at 9 58 28 AM](https://user-images.githubusercontent.com/40807730/89124683-dc114380-d4a6-11ea-96e9-e7478ce6f288.png)
- [ ] `N Intermissions is 0`
![Screen Shot 2020-08-02 at 9 58 42 AM](https://user-images.githubusercontent.com/40807730/89124684-dca9da00-d4a6-11ea-90ea-b328b1dd9c99.png)
- [ ] `N Intermissions is { 0 }`
![Screen Shot 2020-08-02 at 9 58 59 AM](https://user-images.githubusercontent.com/40807730/89124685-dca9da00-d4a6-11ea-82b9-0b68bfd23e1b.png)
- [ ] `N Intermissions eq. 0`
![Screen Shot 2020-08-02 at 9 58 14 AM](https://user-images.githubusercontent.com/40807730/89124686-dca9da00-d4a6-11ea-9802-333895a66d33.png)

**Comment by ybressler** [comment]
An issue with `N No Intermissions --> the code is used on all itercols (dtype = int/float) -- this might not be suitable for when the grammar doesn't make sense.

I'm going to suggest we run with `N Intermissions eq. 0` for this reason.... @jocelyn-shek

**Comment by jocelyn-shek** [comment]
I think that's fine, it's still understandable which is the goal.

**Comment by jocelyn-shek** [comment]
Remove N Unique Theaters from Level 1 summary
