### ISSUE TITLE
Send emails for account creation and approval

### ISSUE THREAD

**Issue by jocelyn-shek** [Broadway-Open-Data/MVP-FrontEnd#22]
Hi ___,

Thank you for creating an Open Broadway Data account.  For security purposes, we manually approve each user before they get access to the website’s full functionality.  We will email you when your account has been approved (within 24 hours).

Best,
The Open Broadway Data Team

Hi ___,

Your Open Broadway Data account has been approved!  Welcome to the growing community of individuals using data to learn more about Broadway.  Now that you are an approved member, you have full access to all of the free functionality Open Broadway Data has to offer - simply sign in to see more.

Happy learning,
The Open Broadway Data Team

**Comment by ybressler** [comment]
Will be implementing soon.
